### ISSUE TITLE
show code area bug

### ISSUE THREAD

**Issue by dogukanuhn** [bilisimtoplulugu/IBT-Web-client#132]
password not match but code are show

![image](https://user-images.githubusercontent.com/42101198/84891730-fd5bd300-b0a4-11ea-91e8-5500d1a293d3.png)

**Comment by UmutKorkmaz** [comment]
This issue is about the Toast component which shows message from the previous trial. It probably occurs because of the asynchronous process of button click events. Also, this issue will be fixed after finding solution to other spamming issues.
