### ISSUE TITLE
Form Validation

### ISSUE THREAD

**Issue by dogukanuhn** [bilisimtoplulugu/IBT-Web-Client#57]
Register form validation such as strong password etc.

**Comment by UmutKorkmaz** [comment]
In this commit, 7d8271e52f126ae6b277a9f946b9be3fdd833c6b I dealt with the email validation problem.

**Comment by UmutKorkmaz** [comment]
In this commit, 377968ca718307fbe17ef5785ab7fadec9a3967d I dealt with password strength
